apiVersion: v1
kind: ServiceAccount
metadata:
  name: tiny-bitly-sa
  namespace: tiny-bitly
  annotations:
    # Workload Identity: bind this KSA to a Google Service Account (GSA)
    iam.gke.io/gcp-service-account: tiny-bitly-gsa@tiny-bitly.iam.gserviceaccount.com
