apiVersion: v1
kind: Service
metadata:
  name: tiny-bitly
  namespace: tiny-bitly
  labels:
    app: tiny-bitly
spec:
  # Easiest way to get a public IP: provision a Google Cloud external load balancer
  # and expose the app on port 80.
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: tiny-bitly
